### PR TITLE
Fix loading copybooks with any encoding

### LINKED ISSUE #956: Specified CPY paths are not followed
Hello again.

When I specify more than one local and/or global paths for copybook include in cobol-lsp.cpy-manager.paths-local setting, only first local and first full paths are searched, others are not.
Even in active paths, not all copybooks are recognized, only few of them.

Here is my cobol-lsp.cpy-manager.paths-local:
"cobol-lsp.cpy-manager.paths-local": [
            "DIR1\\CPY\\COBOL",
            "DIR2\\DIR3\\CPY\\COBOL",
            "C:\\DIR4\\DIR5\\CPY\\COBOL"
        ]
   
Am I doing something wrong? Any idea?

Thanks.

### PR DESCRIPTION
**Pull request by temanbrcom**
Fix #956 

Should be tested with UI tests before merging.

### CODE REVIEW

**Review by asatklichov — APPROVED** [review]
🌵

**Comment by nalmabrcom** [comment]
Test results:
```
====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  LSP/copybook.spec.js                     03:55       22       22        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  LSP/F101836.spec.js                      00:12        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  LSP/F102470.spec.js                      00:29        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  LSP/F95833.spec.js                       04:47        4        2        2        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  LSP/F95834.spec.js                       00:12        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  LSP/F96117.spec.js                       02:19        7        6        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  LSP/F96125.spec.js                       02:38        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  LSP/F97476.spec.js                       07:39        8        6        2        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  LSP/lsp.spec.js                          09:35       22       18        4        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  LSP/zowe.spec.js                         05:38       10        9        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  5 of 10 failed (50%)                     37:29       83       75       8        -        -  
```

File: server/src/main/java/org/eclipse/lsp/cobol/service/utils/WorkspaceFileService.java [hunk 1]
```diff
@@ -65,8 +63,19 @@ public String getNameFromURI(@NonNull String uri) {
   @Nullable
   @Override
   public String getContentByPath(@NonNull Path path) {
-    try (Stream<String> stream = Files.lines(path)) {
-      return stream.reduce((s1, s2) -> s1 + lineSeparator() + s2).orElse("");
+    CharsetDecoder decoder = StandardCharsets.UTF_8.newDecoder();
+    decoder.onMalformedInput(CodingErrorAction.IGNORE);
```
Comment (grianbrcom) [inline server/src/main/java/org/eclipse/lsp/cobol/service/utils/WorkspaceFileService.java:67]: Not really like this idea. Please, check how many bytes it will ignore.

Comment (temanbrcom) [reply server/src/main/java/org/eclipse/lsp/cobol/service/utils/WorkspaceFileService.java:67]: You are right, the text is shifting. I will look for another solution.

Comment (temanbrcom) [reply server/src/main/java/org/eclipse/lsp/cobol/service/utils/WorkspaceFileService.java]: Now it should work fine.

**Review by grianbrcom — APPROVED** [review]
:musical_keyboard:
