### PR TITLE
Inform user about wrong credentials and stop sending other MF requests

### LINKED ISSUE #237: Zowe zOSMF profiles without password are not supported by copybook downloader
## Description ##
The user has a Zowe profile without a password.
Copybook downloader uses this profile to search for copybooks.
In this case, the copybook will not be downloaded with an error.

## Steps to reproduce ##
1. Create a Zowe profile without a password
2. Fetch missing copybook using this profile.
3. Observe error message

## Expected behavior ##
If a password was not provided - ask for a password.
If a password was provided - use it.

## Additional information ##
Most probably changes in Zowe Explorer will be necessary to fix this issue.

### PR DESCRIPTION
**Pull request by grianbrcom**
User was correctly notified if:
* Zowe profile have empty password
* MF API not accessible
* Zowe profile have wrong credentials
* dataset not found

Closes #237

Signed-off-by: Anton Grigorev <anton.grigorev@broadcom.com>

### CODE REVIEW

File: clients/cobol-lsp-vscode-extension/src/services/ZoweApi.ts [hunk 1]
```diff
@@ -41,28 +42,39 @@ export class ZoweApi {
...
+            // tslint:disable-next-line: no-string-literal
+            return result["items"].map((i: any) => i.member);
+        } catch (error) {
+            throw convertError(error);
+        }
     }
 
     public async createSession(profileName: string) {
         const profile = (await new BasicProfileManager(this.createProfileParams()).load({ name: profileName })).profile;
+        if (profile.password === "") {
```
Comment (ishche) [inline clients/cobol-lsp-vscode-extension/src/services/ZoweApi.ts:75]: Can profile be undefined here?

File: clients/cobol-lsp-vscode-extension/src/services/ZoweError.ts [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+    return error;
+}
+
+export class ZoweError extends Error {
+    constructor(message: string, public type: Type = Type.General) {
+        super(message);
+    }
+}
+
+export enum Type {
```
Comment (ishche) [inline clients/cobol-lsp-vscode-extension/src/services/ZoweError.ts:27]: Nice, it looks simpler than a hierarchy of classes. Like, subscribe.

File: clients/cobol-lsp-vscode-extension/src/services/ZoweApi.ts (hunk 1 above)
Comment (grianbrcom) [reply clients/cobol-lsp-vscode-extension/src/services/ZoweApi.ts:75]: Good point! I think that it is possible in case when the user deletes the profile on filesystem right before downloading copybooks.
We need another Error type and Error message for this case. I'll add them.

Comment (grianbrcom) [reply clients/cobol-lsp-vscode-extension/src/services/ZoweApi.ts:75]: Ha! I can't reproduce it.
When I choose the profile, then delete the file and try to download copybook via "quick fix", the IDE asks me to choose the other profile.
When I delete all profiles, IDE shows an error "Zowe profile is missing".
This case already covered.
