### PR TITLE
Fix incorrect error on EXEC CICS

### LINKED ISSUE #965: EXEC CICS statement shows "Missing SQL" error
## Description ##

EXEC CICS statement parses as invalid EXEC SQL statement. 

## Steps to reproduce ##
1. Add a given code example to the `PROCEDURE DIVISION`: `EXEC CICS XCTL123 PROGRAM (XCTL1) END-EXEC.`
2. See an error "Missing token EXEC or SQL"

## Expected behavior ##

No errors are shown, the statement parsed correctly. 

## Environment ##
 - OS: All
 - IDE: All

### PR DESCRIPTION
**Pull request by temanbrcom**
Fix #965

### CODE REVIEW

**Review by zeibura — APPROVED** [review]
LGTM

**Comment by temanbrcom** [comment]
@nalmabrcom

**Comment by nalmabrcom** [comment]
LGTM!
image

File: server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/LocalityFindingUtils.java [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+   */
+  public Locality findPreviousVisibleLocality(Token token, Map<Token, Locality> mapping) {
+    return mapping.computeIfAbsent(
+        token, it -> lookBackLocality(it.getTokenIndex(), mapping, LOOK_BACK_ATTEMPTS_NUMBER));
+  }
+
+  private Locality lookBackLocality(int index, Map<Token, Locality> mapping, int attemptsLeft) {
+    if (attemptsLeft <= 0 || index < 0) return null;
+    return mapping.entrySet().stream()
+        .filter(indexMatchesAndIsVisible(index))
```
Comment (grianbrcom) [inline server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/LocalityFindingUtils.java:51]: I think that instead of recursion it will be easy to filter by the index range:
```
it.getKey().getTokenIndex() <= index && it.getKey().getTokenIndex() >= index - LOOK_BACK_ATTEMPTS_NUMBER
```
After that you can sort them by `index`.

File: server/src/test/java/org/eclipse/lsp/cobol/usecases/TestEnterCompilerDirective.java [hunk 2]
```diff
@@ -32,21 +30,31 @@
...
+          + "       Program-Id. control-dir.";
 
   @Test
   void testNoErrorOnEnterCompilerDirective() {
     UseCaseEngine.runTest(TEXT, ImmutableList.of(), ImmutableMap.of());
   }
 
+  @Test
+  void testNoErrorOnEnterCobolCompilerDirective() {
+    UseCaseEngine.runTest(TEXT, ImmutableList.of(), ImmutableMap.of());
```
Comment (grianbrcom) [inline server/src/test/java/org/eclipse/lsp/cobol/usecases/TestEnterCompilerDirective.java:55]: I bet you want to use `TEXT_COBOL` here.

**Review by grianbrcom — CHANGES_REQUESTED** [review]
Please, fix usecase test.
LocalityFindingUtils is optional.

File: server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/LocalityFindingUtils.java (hunk 1 above)
Comment (temanbrcom) [reply server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/LocalityFindingUtils.java:51]: Not bad, I'll try

**Review by grianbrcom — APPROVED** [review]
:flashlight:
