### PR TITLE
fix: Fix throwing an exception on half typed variable definition

### LINKED ISSUE #1079: Typing a variable definition may produce NPE
## Description ##

An incomplete variable definition `05 asdf PIC X(66` produces NPE

## Steps to reproduce ##
1. Add a variable definition `05 asdf PIC X(66`
2. See the server freezes

## Expected behavior ##

The document is parsed as expected

### PR DESCRIPTION
**Pull request by grianbrcom**
Closes #1079

Signed-off-by: Anton Grigorev <anton.grigorev@broadcom.com>

### CODE REVIEW

File: server/src/test/java/org/eclipse/lsp/cobol/usecases/TestHalfTypedVariableDefinition.java [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+
+import com.google.common.collect.ImmutableList;
+import com.google.common.collect.ImmutableMap;
+import org.eclipse.lsp.cobol.service.delegates.validations.SourceInfoLevels;
+import org.eclipse.lsp.cobol.usecases.engine.UseCaseEngine;
+import org.eclipse.lsp4j.Diagnostic;
+import org.eclipse.lsp4j.DiagnosticSeverity;
+import org.junit.jupiter.api.Test;
+
+/**  */
```
Comment (temanbrcom) [inline server/src/test/java/org/eclipse/lsp/cobol/usecases/TestHalfTypedVariableDefinition.java:25]: Javadoc missing

File: server/src/test/java/org/eclipse/lsp/cobol/usecases/TestHalfTypedVariableDefinition.java [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+          + "       Program-id. HELLO-WORLD.\n"
+          + "       DATA DIVISION.\n"
+          + "       WORKING-STORAGE SECTION.\n"
+          + "       01 {$*COD-RETOUR} PIC X{(|1}{66|2}{|3}";
+
+  @Test
+  void test() {
+    UseCaseEngine.runTest(TEXT, ImmutableList.of(), ImmutableMap.of(
+        "1",
+        new Diagnostic(null, "Extraneous input '(' expected {BINARY, BLANK, COMP, COMPUTATIONAL, COMPUTATIONAL-1, COMPUTATIONAL-2, COMPUTATIONAL-3, COMPUTATIONAL-4, COMPUTATIONAL-5, COMP-1, COMP-2, COMP-3, COMP-4, COMP-5, DISPLAY, DISPLAY-1, DYNAMIC, EXTERNAL, FUNCTION-POINTER, GLOBAL, GROUP-USAGE, INDEX, IS, JUST, JUSTIFIED, LEADING, NATIONAL, OBJECT, OCCURS, PACKED-DECIMAL, PIC, PICTURE, POINTER, POINTER-32, PROCEDURE-POINTER, REDEFINES, SIGN, SYNC, SYNCHRONIZED, TRAILING, USAGE, UTF-8, VALUE, VALUES, VOLATILE, '.', '.'2}",
```
Comment (temanbrcom) [inline server/src/test/java/org/eclipse/lsp/cobol/usecases/TestHalfTypedVariableDefinition.java:38]: Please, split the line not to exceed 120 chars

File: server/src/test/java/org/eclipse/lsp/cobol/usecases/TestHalfTypedVariableDefinition.java [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+            DiagnosticSeverity.Error, SourceInfoLevels.ERROR.getText()),
+        "2",
```
Comment (temanbrcom) [inline server/src/test/java/org/eclipse/lsp/cobol/usecases/TestHalfTypedVariableDefinition.java:40]: The file is not aligned.

**Review by temanbrcom — CHANGES_REQUESTED** [review]

**Review by temanbrcom — APPROVED** [review]
🎃
