### PR TITLE
fix: Fix throwing an exception on half typed DECLARATIVES Section

### LINKED ISSUE #1095: Typing DECLARATIVES Section May Produce Exception
## Description ##

Typing the `DECLARATIVES` section in the `PROCEDURE DIVISION` may fail the server.

## Steps to reproduce ##

1. Type `DECLARATIVES` right after the `PROCEDURE DIVISION` definition.
2. See the server freezes

## Expected behavior ##

The analysis finishes correctly.

### PR DESCRIPTION
**Pull request by grianbrcom**
Closes #1095

Signed-off-by: Anton Grigorev <anton.grigorev@broadcom.com>

### CODE REVIEW

**Review by temanbrcom — APPROVED** [review]
🌮

File: server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDeclarativesSection.java [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+import com.google.common.collect.ImmutableList;
+import com.google.common.collect.ImmutableMap;
+import org.eclipse.lsp.cobol.service.delegates.validations.SourceInfoLevels;
+import org.eclipse.lsp.cobol.usecases.engine.UseCaseEngine;
+import org.eclipse.lsp4j.Diagnostic;
+import org.eclipse.lsp4j.DiagnosticSeverity;
+import org.junit.jupiter.api.Test;
+
+/**
+ * Test that typing the Declaratives section don't produce an Exception.
```
Comment (temanbrcom) [inline server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDeclarativesSection.java:26]: doesn't
