### PR TITLE
fix: Empty continuation line don't throw an exception

### LINKED ISSUE #1078: Continuation Line May Produce an Exception
## Description ##

A continuation line after the DISPLAY statement with an unclosed string literal produces `java.lang.StringIndexOutOfBoundsException`

## Steps to reproduce ##
1. Add code:
```
             DISPLAY '* CODE RETOUR : ' COD-RETOUR '
      -
``` 
2. See server freezes

## Expected behavior ##

The document is parsed as expected

### PR DESCRIPTION
**Pull request by grianbrcom**
Closes #1078

Signed-off-by: Anton Grigorev <anton.grigorev@broadcom.com>

### CODE REVIEW

File: server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/transformer/ContinuationLineTransformation.java [hunk 1]
```diff
@@ -184,20 +163,22 @@ private boolean isBlankLine(CobolLine cobolLine) {
...
   /** Count number of spaces between INDICATOR_AREA and CONTENT_AREA_A */
-  private int countAreaASpaces(String line) {
-    return line.substring(
-            ProcessingConstants.START_INDEX_AREA_A, ProcessingConstants.END_INDEX_CONTENT_AREA_A)
-        .replaceAll("[^ ]", "")
-        .length();
+  private int countLeadingSpaces(String line) {
+    int spaces = 0;
+    int length = line.length();
+    for (int i = 0; i < length; i++)
```
Comment (temanbrcom) [inline server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/transformer/ContinuationLineTransformation.java:176]: It may be replaced with `for(char c : line.toCharArray())`

**Review by temanbrcom — APPROVED** [review]
🍨

**Comment by temanbrcom** [comment]
Please, rephrase the commit message so the message body would start with an imperative verb.

**Review by temanbrcom — APPROVED** [review]
🪀
